import {useState} from 'react';
import {useTranslation} from 'react-i18next';
import {Radar,TriangleAlert,ArrowDownRight,Wind,SlidersHorizontal,Map,Info,ArrowUpRight,CloudRain,Flame,Orbit,ChevronsRight,CalendarDays} from 'lucide-react';
import {IndiaMap,fciColor} from '../components/IndiaMap';
import {Matrix} from '../components/Matrix';
import {PageHeading,PanelTitle,DataState,TextLink} from '../components/Common';
import {Button} from '../components/ui/button';
import {pct} from '../lib/api';
const hazardIcons:any={auto:Radar,rain:CloudRain,heat:Flame,cyclone:Orbit};
export default function Dashboard({feed,day,setDay,hazard,setHazard,onSelect}:any){
const {t}=useTranslation();const [horizon,setHorizon]=useState(false),[all,setAll]=useState(false),[info,setInfo]=useState(false);
const {data,loading,error,retry}=feed;if(loading||error)return <DataState {...{loading,error,retry}}/>;
const regions=data.regions;const cells=regions.flatMap((r:any)=>r.leads.map((l:any)=>({...l,name:r.name,region:r.id})));const lowest=cells.reduce((a:any,b:any)=>a.fci<=b.fci?a:b);const below=regions.filter((r:any)=>r.leads[day-1].fci<65).length;
const hotspots=regions.map((r:any)=>{const risk=r.leads.filter((l:any)=>l.p_bust>=.35);const peak=[...r.leads].sort((a,b)=>b.p_bust-a.p_bust)[0];return {...r,onset:risk[0]?.day,duration:risk.length,peak}}).filter((r:any)=>r.duration).sort((a:any,b:any)=>b.peak.p_bust-a.peak.p_bust);
return <><PageHeading eyebrow="NATIONAL OUTLOOK" title={t('overview')} description={t('subtitle')}><div className="cycle-status"><span className="live-dot"/>Analysis complete<span className="muted">12 regions · 10 lead days</span></div></PageHeading><div className="summary-grid"><div className="summary-card"><div className="stat-label">{t('below')}<Radar size={17}/></div><div className="stat-value" data-testid="below-confidence-count">{below}<span>/ 12 regions</span><div className="mini-bars">{regions.map((r:any)=><i key={r.id} style={{height:8+r.leads[day-1].fci/3,background:fciColor(r.leads[day-1].fci)}}/>)}</div></div><p><span className="warning-dot"/>FCI below 65 on Day {day}</p></div><div className="summary-card"><div className="stat-label">{t('alerts')}<TriangleAlert size={17}/></div><div className="stat-value" data-testid="hotspot-count">{hotspots.length}<span>priority hotspots</span><span className="stat-icon amber"><TriangleAlert size={22}/></span></div><p>Across the 10-day forecast window</p></div><div className="summary-card"><div className="stat-label">{t('lowest')}<ArrowDownRight size={17}/></div><div className="stat-value" data-testid="lowest-confidence">{lowest.fci}<span>FCI · Day {lowest.day}</span><span className="stat-icon red"><ArrowDownRight size={24}/></span></div><p>{lowest.name}</p></div><div className="summary-card"><div className="stat-label">{t('regime')}<Wind size={18}/></div><div className="stat-value regime-value" data-testid="current-regime">Active monsoon<span className="stat-icon teal"><Wind size={24}/></span></div><p><span className="live-dot"/>BSISO phase 3 <span className="stat-divider">|</span> Synthetic scenario</p></div></div>
<div className="forecast-toolbar"><div className="segmented hazard-control">{['auto','rain','heat','cyclone'].map(h=>{const Icon=hazardIcons[h];return <button data-testid={`hazard-${h}`} key={h} onClick={()=>setHazard(h)} aria-pressed={hazard===h} className={hazard===h?'selected':''}><Icon size={15}/>{t(h)}</button>})}</div><span className="toolbar-note"><ShieldIcon/>Calibrated probabilities, not raw spread</span></div>
<div className="dashboard-grid"><section className="map-panel surface"><PanelTitle title={t('map')} subtitle={`India · ${t('day')} ${day} outlook`}><div className="segmented map-mode"><button className={!horizon?'selected':''} onClick={()=>setHorizon(false)} data-testid="map-confidence-mode" aria-label="Confidence map"><Map size={14}/><span>FCI</span></button><button className={horizon?'selected':''} onClick={()=>setHorizon(true)} data-testid="map-horizon-mode" aria-label="Trust horizon map"><CalendarDays size={14}/><span>Horizon</span></button></div></PanelTitle><IndiaMap regions={regions} day={day} onSelect={onSelect} horizon={horizon}/><div className="map-controls"><div className="lead-label"><strong>{t('day')} <span data-testid="selected-lead">{day.toString().padStart(2,'0')}</span></strong><span>MEDIUM-RANGE OUTLOOK</span></div><input type="range" min="1" max="10" value={day} onChange={e=>setDay(+e.target.value)} aria-label="Forecast lead day" data-testid="lead-day-slider"/><div className="slider-labels"><span>Day 1</span><span>Day 5</span><span>Day 10</span></div><div className="fci-legend">{[[90,'high','≥80'],[70,'moderate','65–79'],[50,'low','45–64'],[30,'verylow','<45']].map(([v,label,range]:any)=><span key={label}><i style={{background:fciColor(v)}}/>{t(label)} <small>{range}</small></span>)}</div></div><div className="map-note" data-testid="map-boundary-note">Map not to scale. Boundaries as per Survey of India / Government of India.<a href="/data/map-provenance.json" target="_blank" rel="noreferrer" data-testid="map-provenance-link">NIC source & verification ↗</a></div></section>
<section className="matrix-panel surface"><PanelTitle title={t('matrix')} subtitle="One region. Ten days. A clearer decision window."><button className="icon-btn" aria-label="About trust horizon and bust labels" title="About trust horizon" data-testid="matrix-info" onClick={()=>setInfo(!info)}><Info size={17}/></button></PanelTitle>{info&&<div className="info-inline" data-testid="trust-horizon-info">Trust Horizon is the first day FCI falls below 65; later recovery does not reset it. FCI = 100 × (1 − calibrated probability of bust). A bust is a severe relative error (above the training-only 95th percentile) or a hazard-specific impact error. Moderate relative errors exceed the 90th percentile. Neighbourhood fractions contextualise displacement. Rain: ≥64.5 mm class crossing and ≥30 mm error; heat: 40°C crossing and ≥4.5°C error; circulation: ≥150 km track error. These are prototype triggers, not the complete operational IMD criteria.</div>}<Matrix regions={regions} day={day} onSelect={onSelect}/><div className="matrix-insight"><span className="insight-icon"><SlidersHorizontal size={17}/></span><div><strong>Confidence is a decision, not a promise.</strong><p>View the evidence behind each region’s forecast.</p></div><TextLink to="/reliability" testId="matrix-reliability-link">Track record</TextLink></div></section></div>
<section className="hotspots-section"><PanelTitle title={t('hotspots')} subtitle="Ranked by peak bust probability across the forecast window."><button className="text-link" onClick={()=>setAll(!all)} data-testid="show-all-hotspots">{all?'Show top three':`${t('all')} (${hotspots.length})`}<ArrowUpRight size={14}/></button></PanelTitle><div className="hotspot-grid">{(all?hotspots:hotspots.slice(0,3)).map((r:any,i:number)=><div className="hotspot-card" key={r.id}><div className="hotspot-top"><span className="hotspot-rank">0{i+1}</span><span className={`hazard-tag ${r.peak.hazard}`}>{t(r.peak.hazard)}</span><span className="risk-pill">{pct(r.peak.p_bust)} risk</span></div><h3 data-testid={`hotspot-title-${r.id}`}>{r.name}</h3><p>Onset Day {r.onset}<span>·</span>{r.duration} flagged days<span>·</span>Peak Day {r.peak.day}</p><div className="hotspot-bottom"><div className="spark-strip">{r.leads.map((l:any)=><span key={l.day} style={{background:fciColor(l.fci),height:7+l.p_bust*16}}/>)}</div><Button variant="ghost" size="sm" data-testid={`explore-${r.id}`} onClick={()=>onSelect(r.id,r.peak.day)}>{t('explore')}<ChevronsRight size={14}/></Button></div></div>)}</div>{hotspots.length===0&&<p className="empty-state" data-testid="no-hotspots">No regions cross the alert threshold for this hazard.</p>}</section></>;
}
const ShieldIcon=()=> <span className="live-dot"/>;